### ISSUE TITLE
problems about input

### ISSUE THREAD

**Issue by yuzhenpeng** [harris-fishlab/TRACCER#1]
Hi，

What mean of "Fasta-like file of multiple newick trees". Could you please give some example.

Thank you.

**Comment by STreaster** [comment]
TRACCER now handles both the tabbed format and fasta-like format.

Tabbed format example:
genename1[TAB]newicktree;
genename2[TAB]newicktree;
genename3[TAB]newicktree;

Fasta-like example
\>genename1
newicktree;
\>genename2
newicktree;
\>genename3
newicktree;
